version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "2040"
      TELEGRAM_API_HASH: "b18441a1ff607e10a989891a5462e627"
      TELEGRAM_LOCAL: true
      TELEGRAM_MAX_WEBHOOK_CONNECTIONS: 1000
      TELEGRAM_MAX_CONNECTIONS: 1000
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  nginx:
    build: nginx/.
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8088:80"

volumes:
  telegram-bot-api-data:
